language: c

install:
  - mkdir ~/toolchain
  - "[ $RTT_CPU = 'arm' ] && curl -s https://sourcery.mentor.com/public/gnu_toolchain/arm-none-eabi/arm-2011.03-42-arm-none-eabi-i686-pc-linux-gnu.tar.bz2 | tar xjf - -C ~/toolchain"

before_script:
  - export RTT_EXEC_PATH=~/toolchain/arm-2011.03/bin
  - export RTT_ROOT=`pwd`
  - export RTT_CC='gcc'
  - cd tools

script:
  - python auto-ci.py

notifications:
  email: false

env:
  - RTT_CPU='arm'
