language: c

install:
  - mkdir ~/toolchain
  - "[ $RTT_TOOL_CHAIN = 'sourcery-arm' ] && curl -s https://sourcery.mentor.com/public/gnu_toolchain/arm-none-eabi/arm-2011.03-42-arm-none-eabi-i686-pc-linux-gnu.tar.bz2 | tar xjf - -C ~/toolchain && export RTT_EXEC_PATH=~/toolchain/arm-2011.03/bin || true"

before_script:
  - export RTT_ROOT=`pwd`
  - export RTT_CC='gcc'
  - cd bsp/$RTT_BSP

script:
  - scons

notifications:
  email: false

env:
  - RTT_BSP='at91sam9260' RTT_TOOL_CHAIN='sourcery-arm' 
  - RTT_BSP='efm32' RTT_TOOL_CHAIN='sourcery-arm' 
